apiVersion: v1
kind: Namespace
metadata:
  name: disp-grp14
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: disp-grp14
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: dispgrp14/client:v7
        imagePullPolicy: Always
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
        env:
          - name: UserServiceUri
            value: "https://user-service-svc:5000"
          - name: PurchaseServiceUri
            value: "https://purchase-service-svc:5000"
          - name: SalesServiceUri
            value: "https://sales-service-svc:5000"
          - name: StockServiceUri
            value: "https://stock-service-svc:5000"
          - name: ASPNETCORE_URLS
            value: http://+:5000
---
apiVersion: v1
kind: Service
metadata:
  name: client-svc
  namespace: disp-grp14
spec:
  type: LoadBalancer
  selector:
    app: client
  ports:
  - port: 5000 
    targetPort: 5000
