apiVersion: v1
kind: Namespace
metadata:
  name: disp-grp14
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-service
  namespace: disp-grp14
spec:
  selector:
    matchLabels:
      app: purchase-service
  template:
    metadata:
      labels:
        app: purchase-service
    spec:
      containers:
      - name: purchase-service
        image: dispgrp14/purchase-service:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        ports:
        - containerPort: 5000
        env:
          - name: DBConnection
            value: Server=mssql-deployment.default.svc.cluster.local;Database=grp14-PurchaseService-db;User=SA;Password=F21swtdisp!!;
          - name: ShareBrokerServiceUri
            value: "https://share-broker-svc:5000"
          - name: OwnershipServiceUri
            value: "https://ownership-service-svc:5000"
          - name: ASPNETCORE_URLS
            value: http://+:5000
---
apiVersion: v1
kind: Service
metadata:
  name: purchase-service-svc
  namespace: disp-grp14
spec:
  selector:
    app: purchase-service
  ports:
  - port: 5000 
    targetPort: 5000
