FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

COPY *.csproj .
RUN dotnet restore

COPY ./Protos/TaxServiceGrpc.proto ./Protos/
COPY ./Protos/TransactionServiceGrpc.proto ./Protos/
COPY ./Protos/SharedGrpc.proto ./Protos/
COPY ./Protos/OwnershipServiceGrpc.proto ./Protos/
COPY ./Protos/BankServiceGrpc.proto ./Protos/

COPY . ./source

RUN dotnet publish -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "TransactionService.dll"]