apiVersion: v1
kind: Namespace
metadata:
  name: disp-grp14
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
  namespace: disp-grp14
spec:
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
      - name: bank-service
        image: dispgrp14/bank-service:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: DBConnection
            value: Server=mssql-deployment.default.svc.cluster.local;Database=grp14-BankService-db;User=SA;Password=F21swtdisp!!;
---
apiVersion: v1
kind: Service
metadata:
  name: bank-service-svc
  namespace: disp-grp14
spec:
  selector:
    app: bank-service
  ports:
  - port: 5000 
    targetPort: 5000
